version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /utils/cellprofiler_distributed_utils.wdl
    name: cellprofiler_distributed_utils
  - subclass: WDL
    primaryDescriptorPath: /pipelines/cellpainting/create_load_data.wdl
    name: create_load_data
  - subclass: WDL
    primaryDescriptorPath: /pipelines/cellpainting/cpd_max_projection_pipeline.wdl
    name: cpd_max_projection_pipeline
  - subclass: WDL
    primaryDescriptorPath: /pipelines/cellpainting/cp_illumination_pipeline.wdl
    name: cp_illumination_pipeline
  - subclass: WDL
    primaryDescriptorPath: /pipelines/cellpainting/cpd_analysis_pipeline.wdl
    name: cpd_analysis_pipeline
  - subclass: WDL
    primaryDescriptorPath: /pipelines/mining/cytomining.wdl
    name: cytomining
